### ISSUE TITLE
networkmgr 1.5 dont work , dont show the tray icon.

### ISSUE THREAD

**Issue by javashin** [ghostbsd/ports#2]
networkmgr
ifconfig: interface em0 does not exist
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/share/networkmgr/trayicon.py", line 277, in checkloop
    self.nmMenu = self.nm_menu()
  File "/usr/local/share/networkmgr/trayicon.py", line 116, in nm_menu
    self.wifiListMenu()
  File "/usr/local/share/networkmgr/trayicon.py", line 139, in wifiListMenu
    if wifiData[6] == 'E' or wifiData[6] == 'ES':
IndexError: list index out of range

**Comment by ericbsd** [comment]
Thanks for reporting this, I will look into it as soon that it is possible.

It might have been fixed in master, if you could try it to see it would be very useful.

**Comment by ericbsd** [comment]
Oh sorry I have just noticed that is the ports. I will update has that can.

**Comment by ericbsd** [comment]
I did update the port to 1.6 if you want to give it a try, it would be really appreciated.
